version: '3.8'
services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # uncomment to init the local db

volumes:
  db-data: