services:
  api:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    command: pnpm start:dev
    volumes:
      - .:/measurement

#       empty volume to avoid conflicts with host files
      - /measurement/node_modules
      - /measurement/dist
    depends_on:
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:17.4
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # uncomment to init the local db

volumes:
  db-data: